backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

locale: "es"

collections:
  - name: "galeria"
    label: "Galería de Fotos"
    label_singular: "Foto"
    files:
      - name: "fotos"
        label: "Fotos de la Galería"
        file: "data/galeria.json"
        fields:
          - label: "Fotos"
            name: "fotos"
            widget: "list"
            label_singular: "Foto"
            summary: "{{fields.imagen}}"
            field:
              label: "Imagen"
              name: "imagen"
              widget: "image"
